import type { Technology, NavItem } from "@/types"

export const PERSONAL_INFO = {
  name: "Axel Guerrero Díaz",
  title: "Full Stack Developer",
  tagline: "Building scalable systems with clean, maintainable code",
  location: "Colima, México",
  email: "axelrgdiaz@gmail.com",
  phone: "+52 312 5940609",
  github: "https://github.com/AxelRGDiaz",
  linkedin: "https://www.linkedin.com/in/axel-diaz24/",
  twitter: undefined as string | undefined,
  availability: "Open to new opportunities",
  currentVersion: "v2.0",
  bio: "Internet Technologies Engineer from Universidad de Colima with 3+ years building full-stack web applications. I specialize in Ruby on Rails, Vue 3, and MySQL, and I'm passionate about clean APIs, async processing, and practical solutions to real technical problems.",
  bio_es: "Ingeniero en Tecnologías del Internet por la Universidad de Colima con más de 3 años desarrollando aplicaciones web full-stack. Me especializo en Ruby on Rails, Vue 3 y MySQL, con enfoque en APIs limpias, procesamiento asíncrono y soluciones prácticas a problemas técnicos reales.",
  yearsOfExperience: 3,
  projectsShipped: 10,
  technologiesUsed: 15,
  education: "Ing. en Tecnologías del Internet — Universidad de Colima",
}

export const TECHNOLOGIES: Technology[] = [
  {
    name: "Ruby on Rails",
    category: "framework",
    level: "advanced",
    yearsOfExperience: 3,
    description: "My primary backend framework. I use Rails daily at Mobysuite — building Controllers, Models, Mailers, Workers, and REST APIs.",
    useCases: ["REST APIs", "Background jobs", "Mailers", "ERB views", "DB migrations"],
    projects: ["mobysuite-features"],
  },
  {
    name: "Vue 3",
    category: "framework",
    level: "advanced",
    yearsOfExperience: 3,
    description: "My main frontend framework. I build dynamic UIs with the Composition API and integrate with Rails backends.",
    useCases: ["SPAs", "Dynamic UI components", "Frontend integrations", "Real-time dashboards"],
    projects: ["fullstack-cms", "mobysuite-features"],
  },
  {
    name: "MySQL",
    category: "database",
    level: "advanced",
    yearsOfExperience: 3,
    description: "Primary relational database. I write complex joins, optimize slow queries, and handle schema migrations in production.",
    useCases: ["OLTP systems", "Complex queries", "Query optimization", "Schema migrations"],
    projects: ["fullstack-cms", "mobysuite-features"],
  },
  {
    name: "Sidekiq",
    category: "tool",
    level: "intermediate",
    yearsOfExperience: 2,
    description: "Background job processing in Rails. I use Sidekiq for emails, ZIP generation, and async task processing.",
    useCases: ["Email delivery", "File generation", "Async processing", "Scheduled jobs"],
    projects: ["mobysuite-features"],
  },
  {
    name: "Redis",
    category: "database",
    level: "intermediate",
    yearsOfExperience: 2,
    description: "In-memory store used as Sidekiq backend and for caching in Rails applications.",
    useCases: ["Sidekiq backend", "Caching", "Session store"],
    projects: ["mobysuite-features"],
  },
  {
    name: "Node.js",
    category: "tool",
    level: "intermediate",
    yearsOfExperience: 2,
    description: "I've built REST APIs and IoT data collectors with Node.js. Used Express for backend services.",
    useCases: ["REST APIs", "IoT data collection", "MQTT broker integration", "CLI scripts"],
    projects: ["environmental-monitor", "fullstack-cms"],
  },
  {
    name: "Express.js",
    category: "framework",
    level: "intermediate",
    yearsOfExperience: 2,
    description: "Node.js framework used for building REST APIs in personal projects.",
    useCases: ["REST APIs", "Middleware pipelines", "Route handling"],
    projects: ["fullstack-cms"],
  },
  {
    name: "JavaScript",
    category: "language",
    level: "advanced",
    yearsOfExperience: 3,
    description: "Core language for all frontend work. Used daily with Vue 3 and vanilla JS for DOM interactions.",
    useCases: ["Frontend logic", "API consumption", "DOM manipulation", "Async programming"],
  },
  {
    name: "Docker",
    category: "tool",
    level: "intermediate",
    yearsOfExperience: 2,
    description: "I use Docker for service execution, container management, and debugging in development and production environments.",
    useCases: ["Dev environments", "Service isolation", "Container debugging", "Deployment"],
  },
  {
    name: "MongoDB",
    category: "database",
    level: "intermediate",
    yearsOfExperience: 1,
    description: "Used in the Environmental Monitoring System for storing time-series sensor data.",
    useCases: ["Time-series data", "Sensor telemetry", "Document storage"],
    projects: ["environmental-monitor"],
  },
  {
    name: "MQTT",
    category: "other",
    level: "intermediate",
    yearsOfExperience: 1,
    description: "Lightweight pub/sub messaging protocol used for real-time IoT sensor communication.",
    useCases: ["IoT messaging", "Sensor data", "Real-time telemetry"],
    projects: ["environmental-monitor"],
  },
  {
    name: "Git",
    category: "tool",
    level: "advanced",
    yearsOfExperience: 3,
    description: "Daily driver for version control. Comfortable with branching strategies, PRs, and code reviews.",
    useCases: ["Version control", "Pull Requests", "Code reviews", "Branching"],
  },
  {
    name: "PostgreSQL",
    category: "database",
    level: "intermediate",
    yearsOfExperience: 1,
    description: "Used in personal projects as an alternative to MySQL. Getting comfortable with advanced features.",
    useCases: ["Relational data", "JSONB", "Full-text search"],
  },
  {
    name: "Linux / SSH",
    category: "tool",
    level: "intermediate",
    yearsOfExperience: 2,
    description: "Server administration via SSH for deploying and managing applications on Linux environments.",
    useCases: ["Server deployment", "Remote admin", "Process management"],
    projects: ["environmental-monitor"],
  },
]

export const NAV_ITEMS: NavItem[] = [
  { id: "dashboard", label: "Dashboard", icon: "LayoutDashboard", href: "/" },
  { id: "projects", label: "Projects", icon: "FolderOpen", href: "/projects", badge: "3" },
  { id: "career", label: "Career", icon: "GitBranch", href: "/career" },
  { id: "lab", label: "Tech Lab", icon: "FlaskConical", href: "/lab" },
  { id: "cv", label: "CV Center", icon: "FileText", href: "/cv" },
  { id: "contact", label: "Contact", icon: "MessageSquare", href: "/contact" },
]

export const CURRENT_STATUS = {
  available: true,
  message: "Open to new opportunities",
  message_es: "Abierto a nuevas oportunidades",
  updatedAt: "2026-06-23",
}
